import { useState } from 'react';
import { Mail, MapPin, Phone, Clock, Copy, Check } from 'lucide-react';
import { FaInstagram, FaFacebookF, FaLinkedinIn, FaGithub, FaYoutube } from 'react-icons/fa';
import { JoinButton } from '../home/JoinButton';
import { confirmedExternalUrl } from '../../data/site';
import type { SocialLink } from '../shared/social-types';
const icons={instagram:FaInstagram,facebook:FaFacebookF,linkedin:FaLinkedinIn,github:FaGithub,youtube:FaYoutube};
export interface ContactDetails{email:string|null;address:string|null;phone:string|null;hours?:string|null;city:string}
export function ContactInfo({details,socials,communityUrl}:{details:ContactDetails;socials:SocialLink[];communityUrl:string|null}){
 const [copy,setCopy]=useState('');const safeSocials=socials.filter(s=>confirmedExternalUrl(s.href));
 const email=details.email&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(details.email)?details.email:null;
 const copyEmail=async()=>{if(!email)return;try{await navigator.clipboard.writeText(email);setCopy('Copied!')}catch{setCopy('Copy unavailable. Use the email link instead.')}};
 return <div className="contact-info"><p className="contact-kicker">01 / Start a conversation</p><h2>Let’s build<br/><strong>something together.</strong></h2><p className="contact-intro">A question, an idea, a possible collaboration — we would love to hear what you have in mind.</p><div className="contact-info-rows"><div className="contact-info-row"><span className="contact-icon" data-theme="blue"><Mail size={22}/></span><div><h3>Email</h3>{email?<><a href={`mailto:${encodeURIComponent(email)}`}>{email}</a><button type="button" className="copy-email" onClick={copyEmail} aria-label="Copy contact email">{copy==='Copied!'?<Check size={16}/>:<Copy size={16}/>}</button></>:<p>The chapter email will be shared here when confirmed.</p>}</div></div><div className="contact-info-row"><span className="contact-icon" data-theme="green"><MapPin size={22}/></span><div><h3>Find us</h3><p>{details.address??details.city}</p>{!details.address&&<small>Campus meeting details are coming soon.</small>}</div></div>{details.phone&&<div className="contact-info-row"><span className="contact-icon" data-theme="yellow"><Phone size={22}/></span><div><h3>Phone</h3><a href={`tel:${details.phone.replace(/[^+\d]/g,'')}`}>{details.phone}</a></div></div>}{details.hours&&<div className="contact-info-row"><span className="contact-icon" data-theme="pink"><Clock size={22}/></span><div><h3>Office hours</h3><p>{details.hours}</p></div></div>}</div><p className="contact-copy-status" role="status" aria-live="polite">{copy}</p>{safeSocials.length?<nav className="contact-socials" aria-label="Chapter social profiles">{safeSocials.map(s=>{const Icon=s.platform==="community"?undefined:icons[s.platform];return <a key={s.platform} href={confirmedExternalUrl(s.href)} target="_blank" rel="noopener noreferrer" aria-label={`${s.label} (opens in a new tab)`}>{Icon?<Icon size={20}/>:<img src="/brand/mark-dark.svg" alt=""/>}</a>})}</nav>:<p className="contact-links-pending">Official social links will appear here when confirmed.</p>}<JoinButton url={communityUrl}/></div>;
}
