import { useEffect, useId, useRef, useState, Fragment } from 'react';
import { AnimatePresence, LayoutGroup, motion } from 'motion/react';
import { galleryFilters, galleryPhotos, galleryPage, nextPhotoIndex, type GalleryRecord } from '../../lib/gallery';
import { useMotionPreference } from '../motion/useMotionPreference';
import { AlbumFilter } from './AlbumFilter';
import { PhotoTile } from './PhotoTile';
import { BrandTile } from './BrandTile';
import { Lightbox } from './Lightbox';
export function MasonryGallery({photos,idPrefix='gallery'}:{photos:GalleryRecord[];idPrefix?:string}){
 const records=galleryPhotos(photos),filters=galleryFilters(records),[album,setAlbum]=useState('all'),[limit,setLimit]=useState(24),[selected,setSelected]=useState<string>(),[open,setOpen]=useState(false),[hydrated,setHydrated]=useState(false);
 const reduced=useMotionPreference(),group=useId(),returnFocus=useRef<HTMLElement|null>(null),root=useRef<HTMLDivElement>(null);
 const filtered=galleryPhotos(records,album),page=galleryPage(records,album,limit),index=filtered.findIndex(p=>p.id===selected),photo=filtered[index];
 useEffect(()=>{const read=()=>{const params=new URLSearchParams(location.search),value=params.get('album')??'all';setAlbum(galleryFilters(galleryPhotos(photos)).some(f=>f.value===value)?value:'all');setLimit(24);const id=params.get('photo');setSelected(id??undefined);setOpen(!!id&&galleryPhotos(photos).some(p=>p.id===id));returnFocus.current=root.current?.querySelector('.album-pill')??null;};read();setHydrated(true);window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[photos]);
 const updateUrl=(key:string,value?:string)=>{const url=new URL(location.href);value?url.searchParams.set(key,value):url.searchParams.delete(key);history.pushState(null,'',url.pathname+url.search+url.hash)};
 const changeAlbum=(value:string)=>{setAlbum(value);setLimit(24);setOpen(false);setSelected(undefined);const url=new URL(location.href);value==='all'?url.searchParams.delete('album'):url.searchParams.set('album',value);url.searchParams.delete('photo');history.pushState(null,'',url.pathname+url.search+url.hash)};
 const changeOpen=(value:boolean)=>{setOpen(value);if(!value){const url=new URL(location.href);url.searchParams.delete('photo');history.replaceState(null,'',url.pathname+url.search+url.hash)}};
 const move=(direction:number)=>{if(!filtered.length)return;const next=filtered[nextPhotoIndex(index,direction,filtered.length)];setSelected(next.id);const url=new URL(location.href);url.searchParams.set('photo',next.id);history.replaceState(null,'',url.pathname+url.search+url.hash)};
 return <LayoutGroup id={group}><div ref={root} className="gallery-browser"><AlbumFilter filters={filters} album={album} onChange={changeAlbum} resultsId={`${idPrefix}-results`}/><p className="gallery-result-count" aria-live="polite" aria-atomic="true">{page.total} {page.total===1?'snapshot':'snapshots'}{page.hasMore?` · Showing ${page.photos.length}`:''}</p><motion.div id={`${idPrefix}-results`} className="gallery-masonry" layout={!reduced}><AnimatePresence initial={false} mode="sync">{page.photos.map((item,i)=><Fragment key={item.id}><PhotoTile photo={item} index={i} reduced={reduced} hydrated={hydrated} layoutId={reduced?undefined:`${group}-${item.id}`} onOpen={trigger=>{returnFocus.current=trigger;setSelected(item.id);setOpen(true);updateUrl('photo',item.id)}}/>{(i+1)%9===0&&<BrandTile index={Math.floor(i/9)}/>}</Fragment>)}</AnimatePresence></motion.div>{!page.total&&<div className="gallery-empty"><h3>Memories are on their way.</h3><p>Photos will appear here as albums are confirmed.</p></div>}{page.hasMore&&<button type="button" className="brand-button gallery-load-more" disabled={!hydrated} onClick={()=>setLimit(value=>value+24)}>Load more snapshots <span aria-hidden="true">↓</span></button>}{!hydrated&&<p className="gallery-static-note">Album filters, more photos and the lightbox are available with JavaScript enabled.</p>}</div><Lightbox photo={photo} index={index} total={filtered.length} open={open&&!!photo} onOpenChange={changeOpen} onMove={move} reduced={reduced} layoutId={photo&&!reduced?`${group}-${photo.id}`:undefined} returnFocus={returnFocus}/></LayoutGroup>;
}
